replicaCount: 1

image:
  repository: weburnit/hello
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "multi"

imagePullSecrets: []
nameOverride: "thommy-go"
fullnameOverride: "thommy-go-full"
